var readlineSync = require('readline-sync')
console.log('==================')
console.log('tete do triangulos')
console.log('==================')
var ladoA = Number(readlineSync.question('Digite o 1] lado'))
var ladoB = Number(readlineSync.question('Digite o 2] lado'))
var ladoC = Number(readlineSync.question('Digite o 3] lado'))
console.clear()